### ISSUE TITLE
0.1.0 checklist

### ISSUE THREAD

**Issue by pabsantos** [pabsantos/prfaccidents#1]
- [x] Finish `victims` data
- [x] Fix `uso_solo` in accidents data
- [ ] Write documentation
- [ ] Write README
  - [ ] Add badges
  - [ ] Add logo
- [ ] Write NEWS
- [ ] Write Vignette
- [ ] Make `pkgdown` site

**Comment by pabsantos** [comment]
Consider new functions to read `.parquet` files. For now on, the package will not use `rda` files

- [ ] `prf_read_crashes(year = "all", var = "all")`
- [ ] `prf_read_victims(year = "all", var = "all")`
